### PR TITLE
Support str 8

### PR DESCRIPTION
**Pull request by seppo0010**

### CODE REVIEW

**Comment by seppo0010** [comment]
Discussed in https://groups.google.com/d/msg/redis-db/TxYpTb8uWtk/dZcAu9hb7i4J

**Comment by seppo0010** [comment]
`msgpack` ruby gem was not using str 8 at all up to version 0.5, but since 0.6 it has started to use it. New users will get a failure.

msgpack 0.6:

```
2.1.2 :004 > MessagePack.pack(' ' * 255)
 => "\xD9\xFF                                                                                                                                                                                                                                                               "
```


msgpack 0.5.11:

```
2.1.2 :002 > MessagePack.pack(' ' * 255)
 => "\xDA\x00\xFF                                                                                                                                                                                                                                                               "
```

**Comment by motdotla** [comment]
I also experienced this problem. Would like to see merged :+1:

**Comment by antirez** [comment]
Merged. Integrating into Redis right now.

**Comment by antirez** [comment]
p.s. thank you @seppo0010! I'm not sure how I missed this for a so long time, maybe this was added later in the spec.

**Pull request merged**
